
version: '2'

services:

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:6.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8181

  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - 6379:6379

  elasticvue:
    container_name: "elasticvue"
    image: cars10/elasticvue
    ports:
      - 8181:8080



